module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch Sovereign Archive palette
        'surface': '#10131c',
        'surface-dim': '#10131c',
        'surface-bright': '#353943',
        'surface-container': '#1c2028',
        'surface-container-low': '#181c24',
        'surface-container-high': '#262a33',
        'surface-container-highest': '#31353e',
        'surface-container-lowest': '#0a0e16',
        'surface-variant': '#31353e',
        'surface-tint': '#ffb693',
        'on-surface': '#e0e2ee',
        'on-surface-variant': '#e2bfb0',
        'on-background': '#e0e2ee',
        'background': '#10131c',
        'primary': '#ffb693',
        'primary-container': '#ff6b00',
        'primary-fixed': '#ffdbcc',
        'primary-fixed-dim': '#ffb693',
        'on-primary': '#561f00',
        'on-primary-container': '#572000',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7a3000',
        'inverse-primary': '#a04100',
        'secondary': '#4edea3',
        'secondary-container': '#00a572',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary': '#003824',
        'on-secondary-container': '#00311f',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary': '#e4c368',
        'tertiary-container': '#c7a850',
        'tertiary-fixed': '#ffe08d',
        'tertiary-fixed-dim': '#e4c368',
        'on-tertiary': '#3d2f00',
        'on-tertiary-container': '#4f3d00',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#584400',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#a98a7d',
        'outline-variant': '#5a4136',
        'inverse-surface': '#e0e2ee',
        'inverse-on-surface': '#2d303a',
        // Legacy aliases
        saffron: '#FF6B00',
        'saffron-dim': 'rgba(255,107,0,0.10)',
        navy: '#050810',
        card: '#0D1117',
        'card-2': '#111827',
        'card-border': 'rgba(255,255,255,0.06)',
        'card-border-hover': 'rgba(255,255,255,0.12)',
        gold: '#C8A951',
        emerald: '#10B981',
        sidebar: '#080D1A',
      },
      fontFamily: {
        // Stitch fonts
        headline: ['Newsreader', 'Georgia', 'serif'],
        body: ['Inter', 'DM Sans', 'sans-serif'],
        label: ['Space Grotesk', 'monospace'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        // Legacy aliases
        display: ['"Playfair Display"', 'serif'],
        sans: ['"DM Sans"', 'sans-serif'],
        dmsans: ['"DM Sans"', 'sans-serif'],
        serif: ['"Newsreader"', 'serif'],
        playfair: ['"Playfair Display"', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        saffron: '0 0 40px rgba(255,107,0,0.15)',
        card: '0 4px 24px rgba(0,0,0,0.4)',
      },
    },
  },
  plugins: [],
}
