import { useState } from "react"
import { AnimatePresence, motion } from "framer-motion"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { ShimmerButton } from "@/components/ui/shimmer-button"
import { TypingAnimation } from "@/components/ui/typing-animation"

export default function SummaryPanel({
  summary,
  documentName,
  documentPages,
  metrics,
  onReset,
}) {
  const MotionSection = motion.section
  const [isCopied, setIsCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(summary)
    setIsCopied(true)
    setTimeout(() => setIsCopied(false), 2000)
  }

  const handleDownload = () => {
    const reportContent = `========================
NyayaSetu Analysis Report
========================
Document: ${documentName}
Pages: ${documentPages}
Analyzed: ${new Date().toLocaleDateString("en-IN")}

COMPRESSION METRICS
-------------------
Original Tokens:      ${metrics?.original_tokens ?? 0}
Compressed Tokens:    ${metrics?.compressed_tokens ?? 0}
Tokens Saved:         ${metrics?.tokens_saved ?? 0} (${metrics?.compression_percentage ?? 0}% reduction)
Compression Ratio:    ${metrics?.compression_ratio ?? 0}x
Energy Saved:         ${metrics?.energy_saved_kwh ?? 0} kWh
CO2 Avoided:          ${metrics?.co2_saved_grams ?? 0}g
Cost Saved:           $${metrics?.cost_saved_usd ?? 0}
Information Density:  ${metrics?.information_density ?? 0}

CITIZEN SUMMARY
---------------
${summary}

========================
Generated by NyayaSetu | nyayasetu.vercel.app
Powered by ScaleDown × Groq`

    const blob = new Blob([reportContent], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement("a")
    anchor.href = url
    anchor.download = `${(documentName || "nyayasetu-summary").replace(/\.pdf$/i, "")}-report.txt`
    document.body.appendChild(anchor)
    anchor.click()
    document.body.removeChild(anchor)
    URL.revokeObjectURL(url)
  }

  return (
    <MotionSection
      initial={{ x: 40, opacity: 0 }}
      animate={{ x: 0, opacity: 1 }}
      transition={{ type: "spring", stiffness: 300, damping: 30, delay: 0.3 }}
      className="rounded-2xl border border-card-border bg-navy-light p-6"
      style={{ borderLeft: "4px solid #FF6B00" }}
    >
      <div className="flex items-start justify-between gap-4">
        <p className="max-w-[70%] truncate font-display text-lg italic text-gray-200" title={documentName}>
          {documentName}
        </p>

        <div className="flex flex-wrap items-center justify-end gap-2">
          <Badge className="bg-blue-500/20 text-blue-400 border-blue-500/30">AI Summarized</Badge>
          <Badge className="bg-emerald-500/20 text-emerald-400 border-emerald-500/30">Citizen-Ready</Badge>
        </div>
      </div>

      <Separator className="my-4 opacity-30" />

      <div
        className="max-h-[500px] overflow-y-auto pr-2 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-saffron/60 [&::-webkit-scrollbar-track]:bg-transparent [&::-webkit-scrollbar]:w-1.5"
      >
        <TypingAnimation
          className="font-body text-base leading-8 text-gray-200 whitespace-pre-wrap"
          duration={12}
        >
          {summary}
        </TypingAnimation>
      </div>

      <div className="mt-6 flex flex-wrap gap-3">
        <div className="flex flex-col gap-2">
          <ShimmerButton
            shimmerColor="#FF6B00"
            background="transparent"
            borderRadius="8px"
            onClick={handleCopy}
            className="border border-card-border px-4 py-2 text-sm"
          >
            📋 Copy Summary
          </ShimmerButton>

          <AnimatePresence>
            {isCopied ? (
              <motion.span
                initial={{ opacity: 0, y: -4 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -4 }}
                className="text-xs font-body text-emerald-400"
              >
                ✓ Copied!
              </motion.span>
            ) : null}
          </AnimatePresence>
        </div>

        <Button
          variant="outline"
          onClick={handleDownload}
          className="border-card-border bg-transparent text-sm text-gray-200 hover:bg-navy"
        >
          ⬇️ Download Report
        </Button>

        <Button variant="ghost" onClick={onReset} className="text-sm text-gray-300 hover:text-white">
          🔄 Analyze Another
        </Button>
      </div>
    </MotionSection>
  )
}
